# 문항 1 : Naïve Bayes Classifier

#. 사이트 선택

올리브영 - https://www.oliveyoung.co.kr/

네이버뉴스 - https://news.naver.com/

쿠팡 - https://www.coupang.com/

위 사이트 중 하나를 선택해주세요.

선택한 사이트에서 카테고리 3개를 선택한 뒤, 각각 상품명을 10개씩 수집하고 전처리해주세요.

전처리 된 텍스트에 대해서 카테고리를 분류하는 NBC 문서 분류기를 학습시켜보세요.

In [ ]:
# 올리브영
# 카테고리 : 스킨케어 / 메이크업 / 헤어케어

In [24]:
# 스킨케어

skincare_text = """
    [대용량] 이지듀 EGFx 다운타임 오인트 겔 30ml,
    [10월 올영픽/1+1 기획] 크리니크 쏙보습크림 50ml 단품/기획,
    리얼베리어 익스트림 프로세라 크림 70ml 1+1 기획 (+토너 50ml+로션 40ml),
    [호빵맨 콜라보]이즈앤트리 어니언 뉴페어 겔크림 플러스 50ml 더블 기획 (+마우스패드),
    [건강한 피부를 위한 시작] 세포랩 바이오제닉 에센스 블렌디드 포뮬라 50% (100ml /30ml),
    [1등크림] 에스트라 아토베리어365 크림 80ml 기획(+토너25ml+클렌징폼3g*3EA),
    [속건조필수템] 웰라쥬 리얼 히알루로닉 블루 100 앰플 100ml 기획 (+원데이키트2ea),
    토리든 다이브인 저분자 히알루론산 세럼 50ml 리필 기획 (+50ml 리필+자석인형) (시나모롤),
    [호빵맨 콜라보] [리뷰이벤트] 파넬 시카마누 92세럼 30ml 더블기획 호빵맨 기획,
    [호빵맨 콜라보] [모공/화잘먹]오드로이 모공수축크림 폴리아 콜라겐 100ml 더블기획'
    """

# 메이크업

makeup_text = """
    [10월 올영픽/마뗑킴 에디션] 라네즈X마뗑킴 한정 에디션 3종(쿠션/파우더/틴트) 골라담기,
    [10월 올영픽/마뗑킴 에디션] 라네즈X마뗑킴 네오쿠션 뮤이 15g 기획 (+더플백),
    [NEW/단독기획] 퓌 치크칩 (크림/파우더/베이크드),
    [NEW/10월 올영픽] 클리오 킬 커버 파운웨어 쿠션 단품/기획(+리필+블러쉬밤+퍼프 증정),
    [단종부활템/한정컬러] 유리아쥬 스틱레브르 컬러드 9종,
    [10월 올영픽/마뗑킴 에디션] 라네즈X마뗑킴 에센셜 블러링 피니시 파우더 7g 기획 (+파우치),
    [얼그레이글로스/립밤증정] 퓌 3D 볼류밍 글로스 5.3g (기획/단품),
    [NEW/10월 올영픽]클리오 프로아이팔레트 에어 단품/기획 (+아이 프라이머 밤 증정)(풍년다방 에디션),
    [NEW/10월 올영픽]크리스탈글램틴트 단품/기획 (+코팅 립 마스크 증정) (풍년다방 에디션),
    [7일특가/10월 올영픽] 연작 스킨 퍼펙팅 프로텍티브 베이스 프렙 3종 25ml/40ml 기획
    """

# 헤어케어

haircare_text = """
    [10월 올영픽/몬치치] NEW라보에이치 두피강화샴푸 750ML+100ML [탈모증상완화],
    [10월 올영픽/몬치치] 라보에이치 헤어라인앰플 더블기획(+샴푸50ML),
    아도르 헤어 퍼퓸 플로렛 드 사봉/엔젤뮤게 30ml 기획 (+헤어 오일 10ml 증정),
    [10월 올영픽/몬치치] 라보에이치 비타민&단백질 캡슐 트리트먼트200ML*2+50ML증정,
    [4년 연속 1위] 어노브 딥 데미지 리페어 헤어 마스크 (트리트먼트/헤어팩) 320ml 더블/듀오,
    [10월 올영픽/몬치치] 라보에이치 두피강화클리닉 스케일러 탈모증상완화 208G,
    [10월 올영픽/트롤콜라보] 릴리이브 그로우턴 엑소좀 브러쉬 앰플기획 3종 택1,
    [10월올영픽] 어노브 딥 데미지 리페어 샴푸 500ml 더블/듀오 기획,
    [10월올영픽] 어노브 실크 헤어 오일 에센스 70ml 더블 기획 (텐더블룸/웜페탈),
    [단독기획/미니증정] 아도르 퍼퓸 헤어 오일 80ml 기획 5종 택1
    """

In [32]:
# 원문 데이터를 리스트로 분리
skincare_lines = [line.strip().strip(',') for line in skincare_text.strip().split('\n') if line.strip()]
makeup_lines = [line.strip().strip(',') for line in makeup_text.strip().split('\n') if line.strip()]
haircare_lines = [line.strip().strip(',') for line in haircare_text.strip().split('\n') if line.strip()]

# [문장, 라벨] 구조의 training_set 구축
# 스킨케어 = 0, 메이크업 = 1, 헤어케어 = 2
training_set = []

for doc in skincare_lines:
    training_set.append([doc, 0])
for doc in makeup_lines:
    training_set.append([doc, 1])
for doc in haircare_lines:
    training_set.append([doc, 2])

# 생성된 training_set 양식 확인
print("=== 1단계: training_set 샘플 ===")
print(training_set[:3])

=== 1단계: training_set 샘플 ===
[['[대용량] 이지듀 EGFx 다운타임 오인트 겔 30ml', 0], ['[10월 올영픽/1+1 기획] 크리니크 쏙보습크림 50ml 단품/기획', 0], ['리얼베리어 익스트림 프로세라 크림 70ml 1+1 기획 (+토너 50ml+로션 40ml)', 0]]

In [15]:
%pip install konlpy

Requirement already satisfied: konlpy in c:\users\anaconda\envs\studynlp\lib\site-packages (0.6.0)
Requirement already satisfied: JPype1>=0.7.0 in c:\users\anaconda\envs\studynlp\lib\site-packages (from konlpy) (1.7.1)
Requirement already satisfied: lxml>=4.1.0 in c:\users\anaconda\envs\studynlp\lib\site-packages (from konlpy) (6.1.3)
Requirement already satisfied: numpy>=1.6 in c:\users\anaconda\envs\studynlp\lib\site-packages (from konlpy) (2.0.2)
Requirement already satisfied: packaging in c:\users\anaconda\envs\studynlp\lib\site-packages (from JPype1>=0.7.0->konlpy) (26.3)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import time
from konlpy.tag import Kkma

kkma = Kkma()

stopPos = ['J', 'S', 'NR', 'OL', 'X']
stopwords = [
    '기획', '10월', '올영픽', '단품', '용량', '대용량',
    '/', '[', ']', ',', 'ml', '+', '(', ')', '더블', '증정'
    ]

unique_tokens = set()

for doc, y in training_set:
    raw_tokens = kkma.pos(doc)
    for word, pos in raw_tokens:
        if word in stopwords or pos in stopPos or len(word) == 1:
            continue
        unique_tokens.add(word)     # 단어 목록 정리

In [53]:
import pandas as pd

len_y = 3  # 스킨케어(0), 메이크업(1), 헤어케어(2)
temp = {t: [0] * len_y for t in unique_tokens}

# training_set을 순회하며 카테고리별 단어 빈도수(Count) 누적 계산
for doc, y in training_set:
    raw_tokens = kkma.pos(doc)
    for word, pos in raw_tokens:
        if word in stopwords or pos in stopPos or len(word) == 1:
            continue
        
        if word in temp:
            temp[word][y] += 1

# 판다스 데이터프레임으로 변환 후 형태 확정 (.T)
df = pd.DataFrame(temp, index=['skincare', 'makeup', 'haircare']).T

print("\n=== 2단계: 카테고리별 형태소 빈도수 완성 표 ===")
display(df.head(15))

=== 2단계: 카테고리별 형태소 빈도수 완성 표 ===

     skincare  makeup  haircare
마우스         1       0         0
건조          1       0         0
리얼          2       0         0
마스크         0       1         1
앰플          1       0         2
오일          0       0         3
유리          0       1         0
트롤          0       0         1
트림          1       0         0
아토          1       0         0
러드          0       1         0
세포          1       0         0
루론          1       0         0
브러쉬         0       0         1
특가          0       1         0

In [54]:
targets = df.columns  

k = 0.5
for target in targets:     
    column_name = f'P(w|{target})'
    df[column_name] = (k + df[target]) / (2 * k + df[target].sum())  

import numpy as np
for target in targets:
    conditional_column = f'P(w|{target})'
    log_column = f'Log(P(w|{target}))'
    df[log_column] = np.log(df[conditional_column]) 


df

,skincare,makeup,haircare,P(w|skincare),P(w|makeup),P(w|haircare),Log(P(w|skincare)),Log(P(w|makeup)),Log(P(w|haircare))
마우스,1,0,0,0.020833,0.009259,0.008065,-3.871201,-4.682131,-4.820282
건조,1,0,0,0.020833,0.009259,0.008065,-3.871201,-4.682131,-4.820282
리얼,2,0,0,0.034722,0.009259,0.008065,-3.360375,-4.682131,-4.820282
마스크,0,1,1,0.006944,0.027778,0.024194,-4.969813,-3.583519,-3.721669
앰플,1,0,2,0.020833,0.009259,0.040323,-3.871201,-4.682131,-3.210844
...,...,...,...,...,...,...,...,...,...
에스트,1,0,0,0.020833,0.009259,0.008065,-3.871201,-4.682131,-4.820282
토리,1,0,0,0.020833,0.009259,0.008065,-3.871201,-4.682131,-4.820282
스틱,0,1,0,0.006944,0.027778,0.008065,-4.969813,-3.583519,-4.820282
캡슐,0,0,1,0.006944,0.009259,0.024194,-4.969813,-4.682131,-3.721669
클렌징,1,0,0,0.020833,0.009259,0.008065,-3.871201,-4.682131,-4.820282

In [40]:
for target in targets:
    log_p_targets = np.log(df[targets].sum() / df[targets].sum().sum()).to_dict()
    
log_p_targets

{'skincare': -0.9576759480370094,
 'makeup': -1.2500639115262029,
 'haircare': -1.1094819609050135}

In [42]:
import numpy as np

# 테스트할 새로운 상품명
new_doc = "에스트라 아토베리어 크림 앰플 기획 세트"

# 각 카테고리별 초기 점수를 사전 확률 로그값으로 세팅
result = {target: log_p_targets[target] for target in targets}

# 새로운 문장을 토큰화하여 각 단어의 로그 조건부 확률을 누적 더하기
new_tokens = kkma.pos(new_doc)
for word, pos in new_tokens:
    if word in stopwords or pos in stopPos or len(word) == 1:
        continue
    
    for target in targets:
        log_column = f'Log(P(w|{target}))'
        result[target] += df[log_column].get(word, 0.0)

# 비율 계산
max_log = max(result.values()) # 로그를 씌우면 -값인데, 언더플로우 방지를 위해 최댓값(0에 가까운값으로) 스케일링   
exp_scores = {target: np.exp(score - max_log) for target, score in result.items()}
sum_exp = sum(exp_scores.values())

final_probabilities = {target: score / sum_exp for target, score in exp_scores.items()}

# 최종 예측 결과 출력
print(f"입력한 상품명: '{new_doc}'")
print("-" * 50)
for target, prob in final_probabilities.items():
    print(f"[{target}] 카테고리일 확률: {prob * 100:.2f}%")
print("-" * 50)

best_target = max(final_probabilities, key=final_probabilities.get)
print(f"최종 예측 결과: 이 상품은 [{best_target}] 카테고리입니다!")

입력한 상품명: '에스트라 아토베리어 크림 앰플 기획 세트'
--------------------------------------------------
[skincare] 카테고리일 확률: 97.08%
[makeup] 카테고리일 확률: 1.39%
[haircare] 카테고리일 확률: 1.53%
--------------------------------------------------
최종 예측 결과: 이 상품은 [skincare] 카테고리입니다!

# 문항 2 : 감성분석 (Sentiment Analysis)

#. 사이트 선택

올리브영 - https://www.oliveyoung.co.kr/

네이버뉴스 - https://news.naver.com/

쿠팡 - https://www.coupang.com/

위 사이트 중 하나를 선택해주세요.

선택한 사이트에서 상품을 하나 선택하고, 별점 5개 인 리뷰 10개, 1개인 리뷰 10개를 각각 수집해서 전처리해주세요. (뉴스의 경우 공감이 비공감의 4배 이상인 데이터를 수집해주세요. 반대도 마찬가지입니다.)

전처리 된 텍스트 데이터에 대해서 긍/부정을 구분하여 감성분석을 수행해보세요.

In [44]:
txt_score_1 = """
    최악.롬앤제품 바르면 헤르페스 올라오는데 얘도 어김없이 올라옴 진짜 개 최 악.유리아주 대실망임,
    발색도 별로고 발림도 별로 수분감도 별로 입술 주름에 끼는 립밤이라 안좋았어여 ㅠ 여기 그냥 립밤은 좋은데 이건 별로였어요ㅔ,
    립밤이 안 촉촉하고 매트해요 그리고 색이 진짜 입술 다 뜨게 해요,
    기름지지 않은 컬러 립밤인건 좋은데 색이 너무.. 파워 웜톤인데 fw 컬러라서 이거 잘 맞는 피부 톤은 어떤 톤인지 모르겠어요.,
    기름지지 않은 컬러 립밤인건 좋은데 색이 너무.. 파워 웜톤인데 fw 컬러라서 이거 잘 맞는 피부 톤은 어떤 톤인지 모르겠어요.,
    별 생각없이 컬러가 예뻐서, 유리아쥬라서 믿고 산건데 입술이 따갑고 각질이 일어나네요?? 입술이 찢어진것도 아닌데 계속 따갑고 각질이 생겨요. 뭔가 이상해서 검색해보니 롬ㅇ..콜라보 생각을 못했어요ㅠㅠ 찝찝해서 버렸습니다,
    개별로 진심 이거 왜샀지 …. 너무 별로여서 놀랐어요 진짜 …,
    포도 색아여서 겨쿨들이 사용허기 좋운 그레이프 무스 색상 립밤,
    테스트할때 생각보다 발색이 잘되고 매트해서 불안했지만
유리아쥬의 명성을 믿고 구매했습니다
저 같이 유리아쥬 명성을 믿고 구매하실분 뒤로가기 누르세요
매트하고 하나도 보습이 안되고 발색은 좋지만 지속력은 별로입니다.
우리가 컬러립밤 쓰는 이유는 매마른 입술에 촉촉함과 생기 둘다 주기 위함이잖아요?
보습이 없을거면 더 선택지가 다양하고 발색좋고 지속력 좋은 립스틱을 사죠..
사진은 23호 손등 발색입니다. 5번정도 그었어요,
물먹거나 음식먹을때? 색이뮫어서 좀 불편하네요 음식먹을때도 신경쓰이고 다신 구매 안할거같에요
"""

txt_score_5 = """
웜톤 추천이라니까 사봣음 롬앤 콜라보 좋아요 코랄은 보통 잘안쓰는데 립밤이랑 합쳐진거라 써봅니다,
원래 롬앤 베어그레이프 틴트를 매우 좋아했는데 피부염 이슈로 롬앤을 사용 못 했었어요,
요즘 피부컨디션이 괜찮아지기도했고 베어그레이프 못 잃어서 컬러립밤으로라도 만족하기 위해 구매했습니다 발림성 무난하고 색도 완존 마음에 들어영ㅎㅎ 오히려 틴트보다 가벼워서 좋아요!!!!!,
보습이랑 발색 둘 다 잡은 제품이고 너무 과한 색 싫어하시는 분들 데일리로 바르기 좋아요,
틴트 대신 정말 절 쓰고 있습니다 입술도 촉촉해지고 자연스러워서 3통째 쓰고 있어오,
필요할 때 항상 구매하고 있는 제품입니다. 꾸준히 사용하고 있어서 추천합니다!,
필요할 때 항상 구매하고 있는 제품입니다. 꾸준히 사용하고 있어서 추천합니다!,
컬러립밤류 중에 수분감이 젤 오래남아있는 것 같아용!!!,
아ㅏㅏㅏ 림밥인데 색 이렇게 이쁠일이냐구 단종 절대 안돼요,
색상이 고급스럽고 립밤대체로 사용가능하구 아주 맘에 들어요!
"""

In [46]:
# 원문 데이터를 한 줄(리뷰 1개)씩 분리
neg_reviews = [line.strip() for line in txt_score_1.strip().split('\n') if line.strip()]
pos_reviews = [line.strip() for line in txt_score_5.strip().split('\n') if line.strip()]

# [리뷰내용, 라벨] 구조의 training_set_sentiment 구축
# 부정(별점 1) = 0, 긍정(별점 5) = 1
training_set_sentiment = []

for doc in neg_reviews:
    training_set_sentiment.append([doc, 0])
for doc in pos_reviews:
    training_set_sentiment.append([doc, 1])

print("=== 1단계: 감성분석용 training_set 샘플 (부정 1개, 긍정 1개) ===")
print("부정 샘플:", training_set_sentiment[0])
print("긍정 샘플:", training_set_sentiment[-1])

=== 1단계: 감성분석용 training_set 샘플 (부정 1개, 긍정 1개) ===
부정 샘플: ['최악.롬앤제품 바르면 헤르페스 올라오는데 얘도 어김없이 올라옴 진짜 개 최 악.유리아주 대실망임,', 0]
긍정 샘플: ['색상이 고급스럽고 립밤대체로 사용가능하구 아주 맘에 들어요!', 1]

In [47]:
import pandas as pd
from konlpy.tag import Kkma

kkma = Kkma()

stopPos = ['J', 'S', 'NR', 'OL', 'X']
stopwords = [
    ',', '!','ㅏ','ㅔ','..','...'
]

# 유니크 토큰 수집
unique_tokens_senti = set()
for doc, y in training_set_sentiment:
    raw_tokens = kkma.pos(doc)
    for word, pos in raw_tokens:
        if word in stopwords or pos in stopPos or len(word) == 1:
            continue
        unique_tokens_senti.add(word)

In [48]:
len_y_senti = 2  
temp_senti = {t: [0]*len_y_senti for t in unique_tokens_senti}

# 긍정/부정별 단어 빈도수 계산
for doc, y in training_set_sentiment:
    raw_tokens = kkma.pos(doc)
    for word, pos in raw_tokens:
        if word in stopwords or pos in stopPos or len(word) == 1:
            continue
        if word in temp_senti:
            temp_senti[word][y] += 1

# 감성분석용 최종 빈도수 데이터프레임 빌드
df_senti = pd.DataFrame(temp_senti, index=['negative', 'positive']).T

print("\n=== 2단계: 긍정/부정 단어 빈도수 완성 표 ===")
display(df_senti.head(15))

=== 2단계: 긍정/부정 단어 빈도수 완성 표 ===

       negative  positive
합치            0         1
각질            2         0
우리            1         0
유리            2         0
예쁘            1         0
아니            1         0
정도            1         0
과하            0         1
가능            0         1
마음            0         1
안할거같에         1         0
은데            3         0
사용            1         4
별로            5         0
이쁘            0         1

In [55]:
targets_senti = df_senti.columns  

k = 0.5
for target in targets_senti:     
    column_name = f'P(w|{target})'
    df_senti[column_name] = (k + df_senti[target]) / (2 * k + df_senti[target].sum())  

import numpy as np
for target in targets_senti:
    conditional_column = f'P(w|{target})'
    log_column = f'Log(P(w|{target}))'
    df_senti[log_column] = np.log(df_senti[conditional_column]) 

df_senti

,negative,positive,P(w|negative),P(w|positive),Log(P(w|negative)),Log(P(w|positive))
합치,0,1,0.002890,0.013889,-5.846439,-4.276666
각질,2,0,0.014451,0.004630,-4.237001,-5.375278
우리,1,0,0.008671,0.004630,-4.747826,-5.375278
유리,2,0,0.014451,0.004630,-4.237001,-5.375278
예쁘,1,0,0.008671,0.004630,-4.747826,-5.375278
...,...,...,...,...,...,...
진심,1,0,0.008671,0.004630,-4.747826,-5.375278
버리,1,0,0.008671,0.004630,-4.747826,-5.375278
주기,1,0,0.008671,0.004630,-4.747826,-5.375278
립스틱,1,0,0.008671,0.004630,-4.747826,-5.375278
ㅂ니다,2,5,0.014451,0.050926,-4.237001,-2.977383

In [57]:
for target in targets:
    log_p_targets = np.log(df_senti[targets_senti].sum() / df_senti[targets_senti].sum().sum()).to_dict()
    
log_p_targets

{'negative': -0.4837173050079125, 'positive': -0.9583829473594594}

In [59]:
import numpy as np

# 테스트할 새로운 리뷰
new_doc = """크림 드 베베 레이어
제품 실물샷 제일 비슷하게 컬러 촬영 보정했어요 :)

연한 로즈 빛 핑크로 입에 올라오고요!!
쌩얼에 운동가시거나 할 때 바르면 자연스럽고
화장할 때 베이스로 올려주고 롬앤 컬러 글로스 쫙 올려주먼 넘 예뻐요••

발림성 너무 촉촉하고 대박적
끈적임 없이 가볍게 발리고 촉촉하고 부드럽게 발려요
요 색깔 여쿨라는 구매해도 후회 없으실 거 같아요"""

# 각 카테고리별 초기 점수를 사전 확률 로그값으로 세팅
result = {target: log_p_targets[target] for target in targets_senti}

# 새로운 문장을 토큰화하여 각 단어의 로그 조건부 확률을 누적 더하기
new_tokens = kkma.pos(new_doc)
for word, pos in new_tokens:
    if word in stopwords or pos in stopPos or len(word) == 1:
        continue
    
    for target in targets_senti:
        log_column = f'Log(P(w|{target}))'
        result[target] += df_senti[log_column].get(word, 0.0)

# 비율 계산
max_log = max(result.values()) # 로그를 씌우면 -값인데, 언더플로우 방지를 위해 최댓값(0에 가까운값으로) 스케일링   
exp_scores = {target: np.exp(score - max_log) for target, score in result.items()}
sum_exp = sum(exp_scores.values())

final_probabilities = {target: score / sum_exp for target, score in exp_scores.items()}

# 최종 예측 결과 출력
print(f"입력한 리뷰: '{new_doc}'")
print("-" * 50)
for target, prob in final_probabilities.items():
    print(f"[{target}] 리뷰일 확률: {prob * 100:.2f}%")
print("-" * 50)

best_target = max(final_probabilities, key=final_probabilities.get)
print(f"최종 예측 결과: 이 리뷰는 [{best_target}] 입니다!")

입력한 리뷰: '크림 드 베베 레이어
제품 실물샷 제일 비슷하게 컬러 촬영 보정했어요 :)

연한 로즈 빛 핑크로 입에 올라오고요!!
쌩얼에 운동가시거나 할 때 바르면 자연스럽고
화장할 때 베이스로 올려주고 롬앤 컬러 글로스 쫙 올려주먼 넘 예뻐요••

발림성 너무 촉촉하고 대박적
끈적임 없이 가볍게 발리고 촉촉하고 부드럽게 발려요
요 색깔 여쿨라는 구매해도 후회 없으실 거 같아요'
--------------------------------------------------
[negative] 리뷰일 확률: 0.38%
[positive] 리뷰일 확률: 99.62%
--------------------------------------------------
최종 예측 결과: 이 리뷰는 [positive] 입니다!